### ISSUE TITLE
Exception trying to load embedded libzmq.dll

### ISSUE THREAD

**Issue by danielcrenna** [zeromq/clrzmq#81] opened 2012-08-07 18:36 UTC
Hello,

I was under the impression the pre-release / current CLRZMQ had the libraries bundled in it. I have a strange issue where I have deployed two web applications to the same server, both using these bindings. One of the applications works correctly, the other fails, seemingly trying to load the embedded assembly:

[FileNotFoundException: The specified module could not be found. (Exception from HRESULT: 0x8007007E)]

[FileNotFoundException: Unable to find libzmq.dll on system path or the file found was not the expected file.]
   ZeroMQ.Interop.UnmanagedLibrary..ctor(String fileName) in c:\Users\Johnny\Documents\Projects\clrzmq\src\ZeroMQ\Interop\UnmanagedLibrary.cs:54
   ZeroMQ.Interop.LibZmq..cctor() in c:\Users\Johnny\Documents\Projects\clrzmq\src\ZeroMQ\Interop\LibZmq.NET.cs:48

[TypeInitializationException: The type initializer for 'ZeroMQ.Interop.LibZmq' threw an exception.]
   ZeroMQ.Interop.ContextProxy.Initialize() in c:\Users\Johnny\Documents\Projects\clrzmq\src\ZeroMQ\Interop\ContextProxy.cs:28
   ZeroMQ.ZmqContext.Create() in c:\Users\Johnny\Documents\Projects\clrzmq\src\ZeroMQ\ZmqContext.cs:78
   FID.Sockets.SocketConsumer`1..ctor(String endpoint) in d:\BuildAgent\work\d9ef0f69a8036a89\MyApplication\Sockets\SocketConsumer.cs:29
   MyApplication.CommandModel.ServiceLocator..ctor() +100
   MyApplication.CommandModel.ServiceLocator.get_Instance() +31
   MyApplication.MvcApplication.Application_Start() in d:\BuildAgent\work\d9ef0f69a8036a89\MyApplication.UI\Global.asax.cs:35

**Comment by danielcrenna** [comment] 2012-08-07 19:11
Microsoft Visual Cpp 2010 x64 Redistributable is installed on this machine.

And this is what the Fusion log looks like when I drop the 64 bit build of libzmq.dll into the bin folder of that particular web site:

LOG: This bind starts in default load context.
LOG: Using application configuration file: E:\Websites\MyWebSite\web.config
LOG: Using host configuration file: C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/Temporary ASP.NET Files/root/ed427201/160b3b7b/libzmq.DLL.
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/Temporary ASP.NET Files/root/ed427201/160b3b7b/libzmq/libzmq.DLL.
LOG: Attempting download of new URL file:///E:/Websites/MyWebSite/bin/libzmq.DLL.
LOG: Assembly download was successful. Attempting setup of file: E:\Websites\MyWebSite\bin\libzmq.dll
LOG: Entering download cache setup phase.
ERR: Error extracting manifest import from file (hr = 0x80131018).
ERR: Setup failed with hr = 0x80131018.
ERR: Failed to complete setup of assembly (hr = 0x80131018). Probing terminated.

**Comment by jgoz** [comment] 2012-08-08 19:48
They are embedded into clrzmq.dll in the NuGet package and the zip file from GitHub. If you are compiling it yourself, they do not get embedded (this is part of the packaging process).

Also, if you have other versions of libzmq.dll on any system paths, these may conflict with the embedded versions.

**Comment by danielcrenna** [comment] 2012-08-08 21:03
It seems to be more twisted that that. I tracked down my specific problem to what looks like an exception in the beta 3.X libzmq embedded in your version. In IIS x64 w3wp.exe, it fails to create a context.

To work around it I compiled your sources with a hack to force the extracted assemblies to load from the executing assemblies folder. If left to its own devices, in IIS the assemblies try to write out to the system32 / syswow64 folders that are OS protected from such permissions. That was the first problem and a legitimate bug of the binder.

The second problem was getting around the beta crash, all I did was there was make my embedded assemblies in the custom build point to the stable 2.2 assemblies.

**Comment by glsot** [comment] 2012-08-22 02:02
I have the same trouble with me,and I want to know how to force the extracted assemblies to load from the executing assemblies folder,can you give me a code help to my email glsot1001@126.com.

Thanks in advance.

**Comment by tjrobinson** [comment] 2012-08-24 09:01
@danielcrenna The IIS problem sounds like a problem I had due to IIS not having permissions to create a critical section (in the libzmq.dll code). The code that causes the problem was introduced in 3.x which is why you're not having the problem with 2.2.

I'm currently using a custom build of clrzmq.dll with this change applied:
https://github.com/Artesian/libzmq/commit/23a0ffdf5af7d7c62e729c708f71230c1f98387d

There's a related libzmq JIRA ticket which is apparently now fixed but I've not had time to try it yet:
https://zeromq.jira.com/browse/LIBZMQ-335

**Comment by glsot** [comment] 2012-08-24 09:36
Thanks a lot,my English is poor. And I can't explain my trouble exactly. But for Danielcrenna had the same situation.
Thanks Tjrobinson again and I will try as your advise to make a test.

**Comment by glsot** [comment] 2012-08-24 10:22
I 've tried it in local machine via iis. It's works. Thanks again and wait for the stable 3.x version soon.

**Comment by glsot** [comment] 2012-08-31 10:07
SOS,another problem,I can build(compile) zeromq-3.2.0-rc1 target to x64,but the libzmq.dll can't be loaded by iis(on remote x64 server). But when i build(compile) the source target to x32, It can't run on iis(my local x86 server) very well.

**Comment by glsot** [comment] 2012-08-31 10:17
And if I rename the libzmq-x64-3.0.0.0.dll(from the tmp dir)  to  the system dir as libzmq.dll , the server can run again(but just one website works.)

**Comment by glsot** [comment] 2012-08-31 10:19
And my compile tools is VS2010.

**Comment by jgoz** [comment] 2012-09-07 21:55
@glsot @tjrobinson @danielcrenna 

Sorry for the delay on responding to this issue.

I will try to reproduce this with the latest libzmq, which should have the fix for LIBZMQ-335. If I can't reproduce it, I'll create a new release and ask you to make another attempt.

Thanks for the discussion on this!

**Comment by danielcrenna** [comment] 2012-09-08 00:43
FWIW, I just patched the library so that library resolution can never end
up in an IIS-restricted location (i.e. SYSWOW64, SYSTEM32, or
INETPUB\WWWROOT\BIN) where file permissions are a problem.

I use something like this:

```
    private static string WhereAmI()
    {
        var dir = new Uri(Assembly.GetExecutingAssembly().CodeBase);
        var fi = new FileInfo(dir.AbsolutePath);
        return fi.Directory != null ? fi.Directory.FullName : null;
    }
```

And extract the embedded assemblies / resolve the loaded assemblies to that
location every time.

Cheers,

Daniel

On Fri, Sep 7, 2012 at 5:55 PM, John Gozde notifications@github.com wrote:

> @glsot https://github.com/glsot @tjrobinsonhttps://github.com/tjrobinson
> @danielcrenna https://github.com/danielcrenna
> 
> Sorry for the delay on responding to this issue.
> 
> I will try to reproduce this with the latest libzmq, which should have the
> fix for LIBZMQ-335. If I can't reproduce it, I'll create a new release and
> ask you to make another attempt.
> 
> Thanks for the discussion on this!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zeromq/clrzmq/issues/81#issuecomment-8380229.

## 

Daniel Crenna
Conatus Creative Inc.
cell:613.400.4286

**Comment by danielcrenna** [comment] 2012-09-24 17:23
The issue of finding the correct location rather than trying to write to inetpub/wwwroot/bin or another IIS restricted location is still outstanding, and is separate from the critical section bug when running in the IIS process. Any chance this can be fixed so I don't have to maintain my own version and sync with other improvements?

**Comment by jgoz** [comment] 2012-09-24 17:33
I haven't had any time to work on clrzmq in the last couple of months, but that should change soon. So yes. :)

If you have a fix in your own branch, cleaning it up and submitting a pull request would help me out and speed things along.

**Comment by danielcrenna** [comment] 2012-09-24 18:25
My fix is highly regular to the production environment I'm running it in,
otherwise I would have sent a pull request by now.

**Comment by jgoz** [comment] 2012-09-24 19:43
Fair enough. In that case, I should have time to work on this within the next couple of weeks.

**Comment by danielcrenna** [comment] 2012-09-24 20:09
I will make a pull request for you as soon as my head's out of the vice.

**Comment by jgoz** [comment] 2012-09-24 20:18
Hah, no worries. You posted a good bit of sample code above that I can use as a starting point. But let's see whose head is released first :)

**Comment by glsot** [comment] 2012-09-25 01:52
In fact,after I compiled the libzmq.dll (x64) as a release version,it can run very well on my server(base on x64) now.
The source I built was zeromq-3.2.0-rc1.The only thing I did just as  tjrobinson said.So now I put a seperate clrzmq.dll in the bin,and libzmq.dll in the system dir.
By the way,It doesn't work if you compile as a debug version.Sorry for so late report.

**Closed as completed** 2012-10-13 07:22 UTC
Labels: v3

**Comment by jgoz** [comment] 2012-10-13 07:28
@danielcrenna @glsot 

I should have another beta release by the end of this weekend that will include my attempted fix for this. I'll also do a custom libzmq-3.2.0-rc1 build that includes the patch for LIBZMQ-335.

Once I release it, would you mind testing it in your deployments? I was able to get it working in a local IIS instance, but your environments may be vastly different from mine.

**Comment by danielcrenna** [comment] 2012-10-13 16:15
No problem, we have a complex, multi-site environment I can smoke test it
on. Beats maintaining our own source code!

**Comment by glsot** [comment] 2012-10-15 02:17
I'll deploy the new build on our enviroment.Thanks for your notification .

glsot1001

From: Daniel
Date: 2012-10-14 00:15
To: zeromq/clrzmq
CC: glsot
Subject: Re: [clrzmq] Exception trying to load embedded libzmq.dll (#81)
No problem, we have a complex, multi-site environment I can smoke test it 
on. Beats maintaining our own source code!

**Comment by jgoz** [comment] 2012-10-15 03:00
3.0.0-beta3 was just pushed to NuGet and [downloads](https://github.com/zeromq/clrzmq/downloads). Happy testing and thanks for the patience!

**Comment by glsot** [comment] 2012-10-15 12:52
I've built an new one to our enviroment. It seems it doesn't work yet. Perhaps our enviroment is not clear. Anyway，I will try again tomorrow morning .

How about Daniel, are you Ok?

glsot

From: glsot1001
Date: 2012-10-15 10:19
To: zeromq/clrzmq; zeromq/clrzmq
Subject: Re: Re: [clrzmq] Exception trying to load embedded libzmq.dll (#81)
I'll deploy the new build on our enviroment.Thanks for your notification .

glsot1001

From: Daniel
Date: 2012-10-14 00:15
To: zeromq/clrzmq
CC: glsot
Subject: Re: [clrzmq] Exception trying to load embedded libzmq.dll (#81)
No problem, we have a complex, multi-site environment I can smoke test it 
on. Beats maintaining our own source code!

**Comment by jgoz** [comment] 2012-10-15 15:53
@glsot Do you know if it is failing to extract libzmq.dll, or is it the critical section issue?

**Comment by glsot** [comment] 2012-10-19 09:08
Sorry for so late reply,I've busy for other works these days.

Today,I made a new Dos(console) project. which said cann't find MSVCP110.dll. I searched my system path.just has MSVCP80 MSVCP90 and MSVCP100.dll ,and I can't find MSVCP110.dll. perhaps I need install a new c++ runtime.

glsot1001

From: John Gozde
Date: 2012-10-15 23:53
To: zeromq/clrzmq
CC: glsot
Subject: Re: [clrzmq] Exception trying to load embedded libzmq.dll (#81)
@glsot Do you know if it is failing to extract libzmq.dll, or is it the critical section issue?

**Comment by jgoz** [comment] 2012-10-22 16:57
@glsot You need the [VC++ 2012 redistributable package](http://support.microsoft.com/kb/2019667). But I'm going to go back to using VS2010 to build libzmq.dll for the next release. I forgot that this would result in a new runtime requirement.

Sorry about that!

**Comment by glsot** [comment] 2012-10-23 01:55
Thanks for your reply, I had installed vc++2012, and it does work in our development enviroment.
I will deploy it on our PE today,hope it works as well. 

Thanks again with regard.

glsot1001

From: John Gozde
Date: 2012-10-23 00:57
To: zeromq/clrzmq
CC: glsot
Subject: Re: [clrzmq] Exception trying to load embedded libzmq.dll (#81)
@glsot You need the VC++ 2012 redistributable package. But I'm going to go back to using VS2010 to build libzmq.dll for the next release. I forgot that this would result in a new runtime requirement.
Sorry about that!

**Comment by glsot** [comment] 2012-11-02 01:43
The latest version has worked well on our PE for about 2 weeks ,and it had never broken down. So I think it really does work,the bug can be closed.Thanks again.

**Comment by jgoz** [comment] 2012-11-03 19:17
@glsot Great to hear! Thanks for the update.

**Comment by danielcrenna** [comment] 2012-11-03 20:39
I should chime in: this is running in production now with no issues, in
four different environments. I no longer need to maintain our own hack of
the lib, which is greatly appreciated.

Cheers!

Daniel

**Comment by jgoz** [comment] 2012-11-04 06:38
@danielcrenna Perfect! I'm very happy to hear that. I think that means the next version could be an RC.

**Comment by Belsepubi** [comment] 2013-02-25 10:31
Hi, I´ve been struggling with this issue. I have x64, both clrzmq.dll and libzmq.dll are in website bin -folder. I built those from the source. I also tried rc1 but it just jams te whole IIS. I have IIS 6.1 SP1 Framework 4.0, Windows 7. I have tried to give write permission for IIS user and also copied the lib to System32 and SysWOW64. I always get the same error: 

[FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)]

[FileNotFoundException: Unable to find libzmq.dll on system path or extract it from assembly manifest resources. Inspect Trace output for more details.]
   ZeroMQ.Interop.UnmanagedLibrary..ctor(String fileName) +1417
   ZeroMQ.Interop.LibZmq..cctor() +256

[TypeInitializationException: The type initializer for 'ZeroMQ.Interop.LibZmq' threw an exception.]

etc.

**Comment by tjrobinson** [comment] 2013-02-25 10:37
If you have Windows 7 then you'll be running IIS 7.5 (not 6.1).

Although your operating system is x64, it might be worth checking that your IIS AppPool is running as 64-bit. Look at the Advanced Settings for the AppPool. You need "Enable 32-bit Applications" to be false.

The other thing to try is to "Inspect Trace output for more details". You can get to this using something like DebugView: http://technet.microsoft.com/en-gb/sysinternals/bb896647.aspx

**Comment by Belsepubi** [comment] 2013-02-25 11:08
Yes 7.5 of course. IIS settings were fine. DebugView gave me no help. Depency walker is ok as well.

**Comment by Belsepubi** [comment] 2013-02-25 12:03
Tried on production IIS as well which is IIS 7.0 and windows server 32-bit but got the same error. Of course I put the 32 bit dlls to that.

**Comment by Belsepubi** [comment] 2013-02-25 12:48
Now I got it working with the rc-1.

**Comment by eudaimos** [comment] 2013-04-11 07:33
For anyone else getting to here, I found a nasty setting for project build in VS2012 that can get you to this message.

In Project Properties > Build [tab] > Platform target:
Underneath is a checkbox for "Prefer 32-bit"
Make sure that this is UNCHECKED or when you run on an x64 server, clrzmq will extract and use libzmq-x86-3.0.0.0.dll instead of libzmq-x64-3.0.0.0.dll which is what it needs to run

**Comment by apleshi** [comment] 2013-07-22 02:56
@tjrobinson I am in the same situation as @Belsepubi met, it works fine when I set "Enable 32-bit Applications" to be false, but I have an issue that I have to enable it because our project is using a 32bit dll provided by office, I tried to build libzmq.dll and clrzmq.dll into 32bit, but that didn't work, I think that would be something I missed. So could please help me on this?

**Comment by chriscohoat** [comment] 2014-02-24 17:31
@apleshi Do you recall fixing this issue? We're in the same boat as you and @Belsepubi and can't seem to get the error to go away.

**Comment by shaunol** [comment] 2014-07-22 10:42
Hey guys, I know this is a little old but this is a top result on Google for "libzmq iis" and I'd been having the same issues.

Using http://www.dependencywalker.com/ and loading libzmq.dll (64 bit version) - I found that it was trying to link to C:\windows\system32\msvcp100.dll and msvcr100.dll - which is fine - except dependency walker noted these were actually 32 bit binaries.

Obviously on a 64 bit system, 32 bit binaries shouldn't really exist in system32, despite having already installed the VC2010 SP1 x64 runtime.

So I renamed these two files to .old and ran a repair of the VC2010 SP1 x64 runtime http://www.microsoft.com/en-nz/download/details.aspx?id=13523

This copied new versions of C:\windows\system32\msvcp100.dll and msvcr100.dll - re-running dependency walker confirmed that these were now 64 bit binaries and lo and behold, libzmq is now running correctly :)

So glad to have this fixed, what a crazy problem, hopefully this helps others.

**Comment by gilShin** [comment] 2014-08-17 08:19
Hi,

I still haven't got how to create a clrzmq.dll from source that'll extract the libzmq.dll out of it.
I need version 3.2.2 and there's no such nuget package. 
jgoz said that it is impossible to do it when compiling. My question is how can it be done, if when downloading a clrzmq.dll from a nuget package, it extract the lib just fine.

Thanks
Gil

**Comment by gilShin** [comment] 2014-11-23 16:20
Any news?

Thanks
Gil
