### ISSUE TITLE
NuGet wont install clrzmq on Silverlight 5

### ISSUE THREAD

**Issue by cman122887** [zeromq/clrzmq#39] opened 2011-12-16 18:26 UTC
Nuget tried to install clrzmq. It even had the references in and everything. But as soon as i closed the package manager dialog box the crlzmq reference is removed and i see this in the output. 

> Successfully uninstalled 'clrzmq 2.2.0'.
> Install failed. Rolling back...
> Could not install package 'clrzmq 2.2.0'. You are trying to install this package into a project that targets >'Silverlight,Version=v5.0', but the package does not contain any assembly references that are compatible with that framework. >For more information, contact the package author."

Any help/direction would be very appreciated. Thank you.

**Comment by jgoz** [comment] 2011-12-16 18:31
I think the problem is in the way I organized the NuGet package. I put the binaries in a `lib/net20` folder instead of just `lib/`. I'll have to create a new NuGet package tonight to fix the problem.

In the meantime, you'll have to use the previous package version. Alternately, you can download the zip package from the GitHub repo.

I'll update this issue when I've published a fixed package.

**Comment by cman122887** [comment] 2011-12-16 20:56
Edit: The reference actually worked on the web portion of the project. Just not the application. Which i think is not a problem with clrzmq. I think i may just be trying to use the library in a way it is not supposed to be used. Sorry if i wasted your time.

**Comment by jgoz** [comment] 2011-12-16 21:09
I'm still going to release an updated version with the assemblies in a root /lib folder, which should allow them to be added to Silverlight projects. No apology necessary -- thanks for reporting this!

**Comment by jgoz** [comment] 2011-12-17 01:16
Hi, I updated the packages (v2.2.1). Can you please try again using the new version?

**Comment by cman122887** [comment] 2011-12-17 11:14
Same issue. References fine on the web service side. Not so much on the application side. 
![Imgur](http://i.imgur.com/ZglAJ.png)

This Error pops up when i try to reference it into the application portion:

> You can't add reference to crlzmq.dll, as it was not build against the Silverlight runtime. 
> Silverlight projects will only work with Silverlight Assemblies

Which i think is normal. I know there are libraries that are the same way.
I will play around and see if i can create a silverlight build. In the meantime i will just use zmq in my web service.
Still works. Thanks for the quick assist!

**Comment by jgoz** [comment] 2011-12-17 18:25
Ok, thanks for investigating. I've never actually used Silverlight for anything, but I now recall that it uses a reduced version of the .NET runtime for security and deployment reasons.

It looks like [SL5 supports P/Invoke for full trust applications](http://blogs.msdn.com/b/silverlight_sdk/archive/2011/09/27/pinvoke-in-silverlight5-and-net-framework.aspx). So if you are able to get a working clrzmq build with SL5 support, I'd be happy to take a pull request.

For now, I'm going to close this issue as "won't fix, but may revisit."

**Closed as completed by jgoz** 2011-12-17 18:25 UTC
