### ISSUE TITLE
Unexpected behaviour epgm pub/sub socket in case of intensively use

### ISSUE THREAD

**Issue by suilevap** [zeromq/clrzmq#45] opened 2012-02-07 15:57 UTC
It seems that applications which using clr0MQ library intensively (>1k requests/sec) behave in unexpected way .

When I try to send many messages(~1M) between 2 computers using epmg broadcast (pub/sub), and at some moment (after >200-500k messages which were sent and received successfully) something is going wrong and one computer stops receiving all messages from the other. I tried to stop sending messages for a while, wait some time- all is useless.
Only if I restart one socket (no matter which one: on the first or on the second computer), at the beginning everything is good, but then problem repeats.

Here you can find small test application:
http://dl.dropbox.com/u/16979106/0mq/SimpleBroadcast.zip
To test:
Run application on 2 computers on one lcoal net.
Expected output: 
"Send {0} messages"
and "Received multi {0}"
Real output:
at the beginning: as expected, afters some time only "Send {0} messages"

P.S. 
And moreover sometimes I see crash with message:
"Assertion failed: pending_bytes == 0 (......\src\pgm_receiver.cpp:142)"

**Comment by jgoz** [comment] 2012-02-07 17:23
Hi, a few questions for you:
- What platform are you running on (Win7/.NET/32-bit, Linux/Mono2.x, etc)?
- What version of clrzmq are you using?

There are some known issues with pgm in certain libzmq versions, so this will help identify whether the problem is in clrzmq or in libzmq.

**Comment by suilevap** [comment] 2012-02-07 21:00
1. Win7, .NET4.0, x64( but try x86 too)
2. I think clrzmq 2.2.2 (use Install-Package clrzmq)

**Comment by sustrik** [comment] 2012-02-07 21:47
1. The assertion you are seeing have been fixed in latest development trunk.
2. As for the hang, I guess it's the problem with OpenPGM. When it gets overloaded is sometimes enters a computation-extensive loop used for cleaning the rx window. In such case the CPU utilisation grows to 100% and no more data are received. Try setting PGM rate (ZMQ_RATE option) to some sensible value.

**Comment by suilevap** [comment] 2012-02-07 23:03
1. Thank you for clarification.
2. I tried to use non blocking receive, recv returns control (as I understand it means there is no infinite loop), but after some time without any message, or in other words - the behavior is same.

And I didn't notice any unexpected utilization of CPU (not sure but it was 5-20% on each core), only memory usage was growing.

I tried to use the default rate value, value equal to network capacity, middle value, but I didnt find any difference for problematic behaviour.

**Comment by sustrik** [comment] 2012-02-07 23:21
Ok, then it's a different problem from the one we've been seeing.

**Comment by jgoz** [comment] 2012-02-07 23:28
@sustrik The clrzmq release in question uses libzmq 2.1.11.

I'll investigate this in the next couple days to rule out clrzmq as the issue.

**Comment by suilevap** [comment] 2012-02-08 10:28
@jgoz Thank you in advance. It is important for us to understand what we are doing wrong, or how to avoid this issue.

**Comment by jgoz** [comment] 2012-02-09 04:13
After some investigation, I have a few thoughts. Keep in mind I'm not an expert in PGM.

First of all, I don't think clrzmq is the issue. It's possible that Windows is the issue, but I don't have multiple linux boxes to help me test that theory.

I think the problem is that your program is sending data faster than the PGM receivers can handle it.

I tried manually limiting the send operations to 10,000 msgs/second (by sending 10,000 msgs then using `Thread.Sleep(1000)`) with the following socket options:

``` c#
multiSub.HWM = 0;
multiSub.Rate = 100000; // 100 Mbps
multiSub.RecoveryIvl = 10; // 10 seconds, default

// Same config for multiPub
```

For this configuration and send rate, the programs appeared to run correctly. But if I increased the send rate, even by a factor of 2, it exhibited the behaviour you observed.

Since I'm not familiar with PGM internals, I can't offer any explanation of _why_ the rate must be constrained to such a low value. Perhaps @sustrik may have some ideas. What are typical throughput values over PGM, in your experience?

Finally, the "Assertion failed: pending_bytes == 0 (......\src\pgm_receiver.cpp:142)" error is likely related to LIBZMQ-205, which was fixed in zeromq/libzmq@c34a1443.

**Comment by sustrik** [comment] 2012-02-09 22:15
Well, multicast is something you don't want to use unless you necessarily have to. And if you do, you have to expect it to be pretty capricious. The behaviour heavily depends on different setting on all the layers of the stack, starting from the hardware (switch configuration) up to OpenPGM, 0MQ and application level.

As for this specific problem, I don't believe it's clrzmq issue, so I would create a minimal test case and report a bug for 0MQ core library.

**Comment by jgoz** [comment] 2012-02-09 22:26
Thanks Martin.

@suilevap I'm going to close this issue, as I don't believe it relates to clrzmq. If you have any more evidence pointing to a clrzmq issue, I would be happy to re-open and investigate as necessary.

**Closed as completed by jgoz** 2012-02-09 22:26 UTC

**Comment by suilevap** [comment] 2012-02-14 06:59
Thanks for investigation.

And because it is very serious issue for us, could you please inform me, when issue for core lib of 0MQ will be created, that I will be able to track it's state.

Thank you in advance.

**Comment by sustrik** [comment] 2012-02-14 07:01
Best way is to create a bug report at zeromq.jira.com yourself.
